broker-host: localhost
broker-port: 1883
mapping-type: topic-pair
publish-topic: cs/josev
subscribe-topic: josev/cs
to-mqtt:
  timeout-ms: 500
  request-template:
    id: ${uuid()}
    name: ${verb}
    type: request
    data: ${data}
  request-correlation-path: .id
  response-extraction:
    filter:
      path: .type
      value: response
    data-path: .data
    correlation-path: .id
  
  event:
    registrations:
      # verbs to call to subscribe to events
      - api: josev
        verb: subscribe
    template:
      id: ${uuid()}
      name: ${event_name}
      type: update
      data: ${data}

from-mqtt:
  # the AFB API to call on requests
  api: josev
  request-extraction:
    verb-path: .name
    data-path: .data
    filter:
      path: .type
      value: request

  response-template:
    id: ${request.id}
    name: ${verb}
    type: response
    data: ${data}

  # this will emit an event
  event-extraction:
    event-name-path: .name
    data-path: .data
    filter:
      path: .type
      value: update

